### ISSUE TITLE
тайтл

### ISSUE THREAD

**Issue by Pum-purum** [hybr1dmax/bitrix-env#1]
Я все конечно понимаю, но можно ли как-то объяснить без сленга, прямот вот "ткни сюда и введи сюда вот это"? Я просто программист, ни разу не сисадмин, хочу попробовать разрабатывать проекты локально на Doсker. У меня есть папка D:/projects, в которой я храню папки всех своих проектов. Может быть, вы подскажете, куда и что и как надо сделать, чтобы развернуть локально мой проект из резервной копии, чтобы он был доступен по адресу dev.mycoolproject.com? Сам Docker, слава богу, установил и он даже работает.

**Comment by hybr1dmax** [comment]
Приветствую, мистер Pum-purum. Извиняюсь за задержку с ответом.

Решение в стиле "запустить проект одной командой" в данный момент еще не готово.
Оно будет базироваться на docker-compose. Как только его закончу - залью сюда и задокументирую.

Текущую документацию постарался расписать как можно более подробно, но без фанатизма.
Если вы уже справились с вышеописанным разворачиванием проекта, то поделитесь, не стесняйтесь.

=]

**Comment by Pum-purum** [comment]
Нет, я пришел к выводу, что OpenServer прекрасно справляется с задачей локальной разработки, необходимость в Docker как-то улетучилась.
